# Generated by Django 2.2.6 on 2019-10-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191004_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.CharField(default='m', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
