# Generated by Django 2.2.6 on 2019-10-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191004_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.CharField(default='p', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
