# Generated by Django 2.2.6 on 2019-10-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191004_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.CharField(default='BCDEFG', editable=False, max_length=2000, primary_key=True, serialize=False),
        ),
    ]
