# Generated by Django 2.2.6 on 2019-10-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191004_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='expire_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.CharField(default='56789ba', editable=False, max_length=2000, primary_key=True, serialize=False),
        ),
    ]
