# Generated by Django 2.2.6 on 2019-10-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191004_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.CharField(default='c5X', editable=False, max_length=2000, primary_key=True, serialize=False),
        ),
    ]
